### ISSUE TITLE
Use only free content as examples in documentation and elsewhere.

### ISSUE THREAD

**Issue by jdebp** [ZerioDev/Youtube-Downloader#2]
Given the events of yesterday with youtube-dl, it is very unwise to be using a non-free Petit Biscuit song as an example usage of the tool. Please immediately replace all doco and screenshots, and any commentary in the code itself, with examples that download content that is not restrictively copyright licensed.

* https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md
* https://news.ycombinator.com/item?id=24873742

**Comment by ZerioDev** [comment]
Thanks !
